### GET request for all certificates of a user
GET http://localhost:8080/user/certificates/1
Accept: application/json

### Add new certificate to a user
POST http://localhost:8080/user/certificates/1
Accept: application/json
Content-Type: application/json

{
  "name": "Curso de Fisica Basica",
  "company": "Udemy",
  "expeditionDate": "2018-09-01",
  "credentialId": "456sd114sdg7sadwer98g",
  "credentialURL": "http://udemy.com/certificados/fisica",
  "expirationDate": "2022-09-01"
}

### GET request for an specific certificates of a user
GET http://localhost:8080/user/certificates/1/1
Accept: application/json

### Edit a certificate
PUT http://localhost:8080/user/certificates/edit/3
Accept: application/json
Content-Type: application/json

{
  "name": "Curso de Finanzas",
  "company": "Udemy",
  "expeditionDate": "2018-11-02",
  "credentialId": "4564sdg7sadwer98g987",
  "credentialURL" : "http://udemy.com/certificados/finanzas",
  "expirationDate" : "2020-05-12"
}

### Soft-delete for an especific certificate

DELETE http://localhost:8080/user/certificates/edit/2
Accept: application/json
Content-Type: application/json