### GET request for all certificates of a user
GET http://localhost:8080/user/certificates
Accept: application/json

### Add new certificate to a user
POST http://localhost:8080/user/certificates
Accept: application/json
Content-Type: application/json

{
  "name": "Curso de Finanzas",
  "company": "Udemy",
  "expeditionDate": "2018-11-01",
  "credentialId": "4564sdg7sadwer98g",
  "credentialURL": "http://udemy.com/certificados/finanzas",
  "expirationDate": "2022-11-01"
}

###Edit a certificate
PUT http://localhost:8080/user/certificates/edit/3
Accept: application/json
Content-Type: application/json

{
  "name": "Curso de Finanzas",
  "company": "Udemy",
  "expeditionDate": "2018-11-02",
  "credentialId": "4564sdg7sadwer98g987",
  "credentialURL" : "http://udemy.com/certificados/finanzas",
  "expirationDate" : "2020-05-12"
}
### Create new user

POST http://localhost:8080/newuser
Accept: application/json
Content-Type: application/json

{
  "name": "lorito",
  "surname": "Fernandez",
  "nickName": "El yepas",
  "email": "example@gmail.com"
}

###

POST http://localhost:8080/my-projects/1
Accept: application/json
Content-Type: application/json

{
  "projectTitle": "Esto es una prueba 2",
  "description": "es un poyecto es una prueba 2",
  "abilities": "El Nerd 2",
  "benefits": "mucho dinero 2",
   "status" : "0"
}
###
///
PUT http://localhost:8080/my-projects/edit/3
Accept: application/json
Content-Type: application/json

{
  "projectTitle": "Autos voladores",
  "description": "es un poyecto muy nuevo",
  "abilities": "El Nerd",
  "benefits": "mucho dinero ",
  "status" : "0"
}

###
GET http://localhost:8080/my-projects/2
Accept: application/json
###
///project-feed/{userid}

GET http://localhost:8080/my-projects/project-feed/1
Accept: application/json

###
///list/{userid}
GET http://localhost:8080/my-projects/list/1
Accept: application/json

###
///{projectid}/user-request
GET http://localhost:8080/my-projects/3/user-request
Accept: application/json
