GET http://localhost:8080/user/notification/1
Accept: application/json
###
///list/work_on/{userid}
GET http://localhost:8080/user/notification/list/1
Accept: application/json

###
///update/{idnotification}/{status}
PUT http://localhost:8080//user/notification/update/1/2
Accept: application/json