POST http://localhost:8080/paymentPlan
Accept: application/json
Content-Type: application/json

{
  "plan": "2 mes",
  "description": "2 meses de publicidad para tu proyecto",
  "cost": "450.99",
  "duration": "2",
  "creationDate": "2020-10-15"
}
###