###
POST http://localhost:8080/paymentPlan
Accept: application/json
Content-Type: application/json

{
  "plan": "1 año",
  "description": "1 año de publicidad para tu proyecto",
  "cost": "550.20",
  "duration": "1",
  "creationDate": "2020-02-03"
}

