
POST http://localhost:8080/my-projects/1
Accept: application/json
Content-Type: application/json

{
  "projectTitle": "Esto es una prueba 2",
  "description": "es un poyecto es una prueba 2",
  "benefits": "mucho dinero 2",
  "status" : 1
}
###
///
PUT http://localhost:8080/my-projects/edit/3
Accept: application/json
Content-Type: application/json

{
  "projectTitle": "Autos voladores",
  "description": "es un poyecto muy nuevo",
  "benefits": "mucho dinero ",
  "status" : 1
}

###
GET http://localhost:8080/my-projects/1
Accept: application/json
###
///project-feed/{userid}

GET http://localhost:8080/my-projects/project-feed/1
Accept: application/json

###
///list/{userid}
GET http://localhost:8080/my-projects/list/1
Accept: application/json

###

///{projectid}/user-request
GET http://localhost:8080/my-projects/3/user-request
Accept: application/json
###
///{projectid}/user-members

GET http://localhost:8080/my-projects/3/user-members
Accept: application/json
###
///list/work_on/{userid}
GET http://localhost:8080/my-projects/list/work_on/3
Accept: application/json