### POST new tag user
POST http://localhost:8080/tags/user/1
Accept: application/json
Content-Type: application/json

{
  "tag": "c++",
  "verified": 1
}

### GET tag by name

GET http://localhost:8080/tags/python
Accept: application/json
###get user tag
GET http://localhost:8080/tags/user/1
Accept: application/json

### GET All verified tags
GET http://localhost:8080/tags
Accept: application/json