### Create new user
POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
  "name": "Ronald ",
  "surname": "Romero",
  "username": "ronmen",
  "email": "ronmen@gmail.com"
}

### Get user 1
GET http://localhost:8080/users/2
Accept: application/json

### Update user 1
PUT http://localhost:8080/users/1
Accept: application/json
Content-Type: application/json

{
  "name": "Juan",
  "surname": "Fernandez",
  "username": "El paisano",
  "email": "example@gmail.com",
  "description": "Me gusta el sql",
  "image": "B64encondeimageOrDirOfFile",
  "cellphone": "75281857"
}
###